site_name: Документация MkDocs
site_description: Тестовый сайт с документацией на MkDocs.

theme: material

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: start.md
  - About: about.md
